import React, { PureComponent, useEffect, useState } from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';


export default class Users extends PureComponent {

    state = {
        data: [],
        opacity: {
            user: 1,
            barber: 1,
        },
    };

    handleMouseEnter = (o) => {
        const { dataKey } = o;
        const { opacity } = this.state;

        this.setState({
            opacity: { ...opacity, [dataKey]: 0.5 },
        });
    };

    handleMouseLeave = (o) => {
        const { dataKey } = o;
        const { opacity } = this.state;

        this.setState({
            opacity: { ...opacity, [dataKey]: 1 },
        });
    };

    render() {
        const { opacity } = this.state;

        return (
            <div style={{ width: '100%', marginTop: "20px" }}>
                <ResponsiveContainer width="100%" height={300}>
                    <LineChart
                        width={500}
                        height={300}
                        data={this.props.data}
                        margin={{
                            top: 5,
                            right: 30,
                            left: 20,
                            bottom: 5,
                        }}
                    >
                        <CartesianGrid strokeDasharray="3 3" />
                        <XAxis dataKey="name" />
                        <YAxis />
                        <Tooltip />
                        <Legend onMouseEnter={this.handleMouseEnter} onMouseLeave={this.handleMouseLeave} />
                        <Line type="monotone" dataKey="barber" strokeOpacity={opacity.barber} stroke="#8884d8" activeDot={{ r: 8 }} />
                        <Line type="monotone" dataKey="user" strokeOpacity={opacity.user} stroke="#82ca9d" />
                    </LineChart>
                </ResponsiveContainer>
                <p className="notes">Tips: These detail are auto generated by the system on the proformance of your app!</p>
            </div>
        );
    }
}
